# Generated by Django 6.0.4 on 2026-04-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tópico')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='gerador.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado (LaTeX)')),
                ('alt_1', models.CharField(max_length=500, verbose_name='Alternativa 1')),
                ('alt_2', models.CharField(max_length=500, verbose_name='Alternativa 2')),
                ('alt_3', models.CharField(max_length=500, verbose_name='Alternativa 3')),
                ('alt_4', models.CharField(max_length=500, verbose_name='Alternativa 4')),
                ('alt_5', models.CharField(max_length=500, verbose_name='Alternativa 5')),
                ('alt_6', models.CharField(max_length=500, verbose_name='Alternativa 6')),
                ('alt_7', models.CharField(max_length=500, verbose_name='Alternativa 7')),
                ('alt_8', models.CharField(max_length=500, verbose_name='Alternativa 8')),
                ('alt_9', models.CharField(max_length=500, verbose_name='Alternativa 9')),
                ('alt_10', models.CharField(max_length=500, verbose_name='Alternativa 10')),
                ('correta', models.IntegerField(verbose_name='Qual a correta? (1 a 10)')),
                ('resolucao', models.TextField(verbose_name='Resolução Comentada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='gerador.topico')),
            ],
        ),
    ]
