# Generated by Django 6.0.4 on 2026-04-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='codigo',
        ),
    ]
