# Generated by Django 6.0.4 on 2026-06-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0002_remove_disciplina_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_contexto', models.TextField(help_text='Ex: Focado em biologia marinha, aquicultura e clima.')),
            ],
        ),
        migrations.RemoveField(
            model_name='topico',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='topico',
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='EsqueletoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopico', models.CharField(blank=True, help_text='Ex: Eventos Independentes', max_length=200, null=True)),
                ('enunciado_base', models.TextField(help_text='A estrutura matemática rígida da questão.')),
                ('instrucoes_ia', models.TextField(help_text='Regras de sorteio e contexto para o Gemini.')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerador.topico')),
            ],
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
