# Generated by Django 6.0.4 on 2026-07-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0003_curso_remove_topico_disciplina_remove_questao_topico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior')], default='superior', max_length=20),
        ),
    ]
