# Generated by Django 6.0.4 on 2026-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0004_curso_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior')], max_length=20),
        ),
    ]
