"""
Django settings for statlab project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path
import dj_database_url # Importa o leitor de conexões de banco de dados

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Na nuvem, ele pega a chave segura; no PC local, ele usa essa chave temporária.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-xw3)kex6o#k38%hcbu2a98@cs=j=raz=9+w1agr%j7ex4wnl5%')

# SECURITY WARNING: don't run with debug turned on in production!
# O Render colocará RENDER=True, então o DEBUG ficará False automaticamente na nuvem.
#DEBUG = 'RENDER' not in os.environ
DEBUG = True
# Permitir que qualquer servidor hospede a aplicação (O Render usa isso)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gerador',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # IMPORTANTE: O WhiteNoise serve os arquivos CSS/JS em produção!
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statlab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'statlab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuração dinâmica:
# Se o Render fornecer a URL do banco de dados (Neon), ele se conecta lá.
# Se não (no seu PC local), ele usa o sqlite3 por padrão.
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Aqui está a conexão oficial do novo banco Neon (StatLab Clássico)
        default='postgresql://neondb_owner:npg_uN2cHIjPJ1BV@ep-icy-river-ac9fmq5p-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Deixando o sistema em Português e no Fuso de Brasília
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Diretório onde o Django vai reunir todos os arquivos estáticos na nuvem
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilita compressão e controle de cache para os arquivos CSS/JS no servidor
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'AIzaSyCcogW3-saEFYcNa69hpt3EV51Vi7vUZ2c')